### ISSUE TITLE
upgrade Debian 8 Fail

### ISSUE THREAD

**Issue by juanjosepablos** [OCSInventory-NG/OCSInventory-Server#12]
Hi,
I had upgrade my server from Debian 7 to Debian 8. I am using OCS NG 2.1.2
 And I found a couple of issues.
1) /etc/apache2/conf.d not longer valid
 mv ocsinventory-reports.conf and z-ocsinventory-server.conf /etc/apache2/conf-enabled 
a2enconf ocsinventory-reports
a2enconf z-ocsinventory-server

2) Perl Path 
mv /usr/local/share/perl/5.14.2  /usr/local/share/perl/5.20.2

3)  require "SOAP_USER" error
This is just a note for anyone seen this bug report. 
Change Require  "SOAP_USER"  >  Require user "SOAP_USER" on z-ocsinventory-server.conf

**Comment by gillesdubois** [comment]
Hi,

2.1.2 has some compatibility issues with apache 2.4.
anyway these problems are just related with the apache configuration.
The perl path problems you encountered come from your upgrade ... if you upgrade your system and your dependencies you should re-run the setup.sh in order to redefine perl and other path.

Regards,
Gilles Dubois.
