### ISSUE TITLE
AGENT => Failed to send Prolog <Couldn't connect to server>

### ISSUE THREAD

**Issue by rrajesh011** [OCSInventory-NG/OCSInventory-Server#218]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Windows 10

### Server informations
Perl version : v5.16.3
Mysql / Mariadb / Percona version :  Mysql 5.6

### Server installation method ( Only one choice )
- [ ] RPM Package
- [x] Install SH
- [ ] Manual installation

### OCS Inventory informations
Ocs server version : 2.4.1

### Problem's description
*I have installed windows agent in my windows 10 system. Agent is not synchronizing to server daily. i have set prolog frequent to 4 hrs. Sometimes i get Inventory send successful and sometime i get error like `AGENT => Failed to send Prolog <Couldn't connect to server>` or `ERROR *** AGENT => Failed to send Inventory <HTTP Status Code #500>`. Inventory.log and config file attached.*

[ocs.ini.txt](https://github.com/OCSInventory-NG/OCSInventory-Server/files/4279822/ocs.ini.txt)
[ocs.log](https://github.com/OCSInventory-NG/OCSInventory-Server/files/4279823/ocs.log)

**Comment by gillesdubois** [comment]
Hi @rrajesh011 ,

To me it looks more like a network issue than an OCS Inventory issue.
Could you check the server's log ?

Regards,
Gilles Dubois.

**Comment by rrajesh011** [comment]
Hi @gillesdubois, thanks for reply, do you want apache server log?

**Comment by gillesdubois** [comment]
Hi,

Sorry for the delay.

Indeed it would be appreciated

**Comment by rrajesh011** [comment]
DBD::mysql::db do failed: Duplicate entry '4574425' for key 'PRIMARY' at /usr/local/share/perl5/Apache/Ocsinventory/Server/System.pm line 212.
DBD::mysql::db do failed: Lock wait timeout exceeded; try restarting transaction at /usr/local/share/perl5/Apache/Ocsinventory/Server/Inventory/Update.pm line 88.


 70
 71   # The computer exists.
 72   # We check if this section has changed since the last inventory (only if activated)
 73   # We delete the previous entries
 74   if($Apache::Ocsinventory::CURRENT_CONTEXT{'EXIST_FL'}){
 75     if($ENV{'OCS_OPT_INVENTORY_DIFF'}){
 76       if( _has_changed($section) ){
 77         &_log( 113, 'inventory', "u:$section") if $ENV{'OCS_OPT_LOGLEVEL'};
 78         $sectionMeta->{hasChanged} = 1;
 79       }
 80       else{
 81         return 0;
 82       }
 83     }
 84     else{
 85       $sectionMeta->{hasChanged} = 1;
 86     }
 87     if( $sectionMeta->{delOnReplace} && !($sectionMeta->{writeDiff} && $ENV{'OCS_OPT_INVENTORY_WRITE_DIFF'}) ){
 88       if(!$dbh->do("DELETE FROM $section WHERE HARDWARE_ID=?", {}, $deviceId)){
 89         return(1);
 90       }
 91     }
 92   }
 93

**Comment by rrajesh011** [comment]
10.9.64.44 - - [20/Aug/2020:12:28:53 +0530] "POST /ocsinventory HTTP/1.1" 500 536 "-" "OCS-NG_unified_unix_agent_v2.3.1" "-" "-" 61036363

**Comment by gillesdubois** [comment]
Hi @rrajesh011 

80k assets is indeed a lot. Most of the time fine tunning is needed after ~50k assets in order to get better performence.
Here is a list of some things that you can do to lower the Backend load average : 

1/ On OCS Inventory configuration

Webconsole : 
Inventory - INVENTORY_DIFF => ON 
Inventory - INVENTORY_WRITE_DIFF => ON
Server - PROLOG_FREQ => If lower then 4 hours raise to 4 hours.
Interface - TAB_CACHE => ON

2/ On the MySQL

I won't explain every parameters but in that case you have to rely on caching the most solicited tables in the database like hardware / netmap / config.

You can also make the SQL Server rollback if a transaction fail which will have a lower impact in the database if a transaction fail a whatever reason.

OCS do use memory tables, if you have a MySQL Master / Slave configuration please don't replicate them, they don't have any important informations and will considerably slow you SQL Server.

Regards,
Gilles Dubois.

**Comment by rrajesh011** [comment]
Hi @gillesdubois,

i am unable to understand this point can you please explain a bit:

`You can also make the SQL Server rollback if a transaction fail which will have a lower impact in the database if a transaction fail a whatever reason`

**Comment by gillesdubois** [comment]
Hi,

```
DBD::mysql::db do failed: Lock wait timeout exceeded; try restarting transaction
```

As you can see after the lock exceeded its insert time it will try to restart the transaction.
You can configure the SQL Server to drop the transaction instead on re-trying it.

Regards,
Gilles.
