### ISSUE TITLE
Can't load SOAP::Transport::HTTP* - Web service will be unavailable at apache2 start

### ISSUE THREAD

**Issue by andreaferraris** [OCSInventory-NG/OCSInventory-Server#23]
Maybe I'm in the wrong place, if so I can understand to go away either in English, either in French, so feel free to replay in the language you like best.

What in the subject is what I see in the apache log error at startup on Ubuntu 14 server lts (about 1 GB RAM, 2 CPU, about 100 GB disk) as VM under VMWare 5.5

 After goint to the end (of the setup some time) I notices at setup of OCSInventory that I've got:

  +----------------------------------------------------------+
  |         Checking for optional Perl Modules...            |
  +----------------------------------------------------------+

  Checking for Apache2::SOAP PERL module...
  **\* Warning: PERL module Apache2::SOAP is not installed !
  This module is only required by OCS Inventory NG SOAP Web Service.
  Do you wish to continue ([y]/n] ?n

  Installation aborted !

  But if I look for such module to install it, I get:

  root@mui:~/OCSNG_UNIX_SERVER-2.2.1# cpan install  Apache2::SOAP
  Loading internal null logger. Install Log::Log4perl for logging messages
  Reading '/root/.cpan/Metadata'
    Database was generated on Fri, 29 Jul 2016 02:29:03 GMT
  Apache2::SOAP is up to date (0.73).
  root@mui:~/OCSNG_UNIX_SERVER-2.2.1#

  So I can't understand why the setup tell me that Apache2::SOAP is not
  installed when if I try to install it I give the reply that it is
  already installed.

  Some hints, please?

Regards,  Andrea

**Comment by gillesdubois** [comment]
Hi,

This is a known bug on the ocs setup some SOAP version are not properly detected.
As long as this is a optional module you can continue and ignore this error message

Regards,
Gilles Dubois.

**Comment by alexwbaule** [comment]
The problem is:

The setup.sh uses perl -mApache2::SOAP -e 'print "PERL module Apache2::SOAP is available\n"' to detect if Apache2::SOAP is installed, running this by hand, get this error:
Unsupported version of mod_perl at /usr/local/share/perl5/SOAP/Transport/HTTP2.pm line 85.

This happens because this module, check if the mod_perl is the 2.x , in line (67 to 85) that check if exist the MOD_PERL_API_VERSION ENV variable, but this variable is create in some HTTP environment, no in "console" use, If you set manual "export MOD_PERL_API_VERSION=2" and run again the "perl -mApache2::SOAP" you dont get the Error Anymore.

Ok, can i set this Manually and run the setup.sh ? No.

Because exporting this variable to the ENV, the perl-Apache-DBI fails !

Undefined subroutine &Apache2::Module::loaded called at /usr/local/share/perl5/Apache/DBI.pm line 374.

I Think the solution is, setup.sh checks if exist Apache2::SOAP in other way, i dont know how.

**Comment by alexwbaule** [comment]
What i have done:

in setup.sh, line 1001, add inside parentheses "export MOD_PERL_API_VERSION=2" and the line becomes:

(export MOD_PERL_API_VERSION=2 ; $PERL_BIN -mApache2::SOAP -e 'print "PERL module Apache2::SOAP is available\n"' >> $SETUP_LOG 2>&1)

And The detection was OK.

**Comment by gillesdubois** [comment]
Hi,

Setup has been updated and now fully support Apache2::SOAP module.

Regards,
Gilles Dubois.

**Comment by danielar-hyuna** [comment]
Hi, i have installed ocsng from a docker image and i am getting these error in apache log file

ocsinventory-server: Bad setting. `INVENTORY_ON_STARTUP` is not set. Default: `0`
ocsinventory-server: Can't load SOAP::Transport::HTTP* - Web service will be unavailable

**Comment by olih10200** [comment]
maybe updated two years before, but this time the bug alive .... today cloned repo

**Comment by MarcosTecnitia** [comment]
December 2018, OCS-Inventory Server 2.5 and the bug is alive  
[https://i.postimg.cc/L6Sp9jx1/BugOCS.jpg](url)

**Comment by Rodgelius** [comment]
06.02.2019, OCS-Inventory Server 2.5 and the bug is alive...

**Comment by ll4mat** [comment]
05.04.2019 OCS-Inventory Server 2.5 and the bug is still alive...
