### ISSUE TITLE
http - SNMP

### ISSUE THREAD

**Issue by Artem-Mamzikov** [OCSInventory-NG/OCSInventory-Server#271]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian 9 64-bit

### Server informations
Perl version : 5.24
Mysql  Mariadb 

### OCS Inventory informations
Ocs server version : 2.8

### Problem's description
error: agent must communicate using https to be able to get SNMP communities (only affects OCS unix agent)

Good afternoon! I have an internal LAN of 800 hosts, I want to collect data over snmp, but I don't have (I don't use) an ssl certificate for https. I have a normal http connection. Is there any way to enable configure the search and collection of information about snmp over http? I think this option will be useful to many who use for a local network over http and will be useful. I also understand that it is not so secure to transfer data over http, but this is a closed local network.
I will be very grateful if you help!

**Comment by gillesdubois** [comment]
Hi @Artem-Mamzikov 

Having SNMP over HTTPS only is for security reason.
For your point of view it seem that the 800 Host LAN is completely isolated and thus using HTTP is not a big deal.

However, we can't access your request, having SNMP over HTTP can be disatrous for most of the OCS Inventory installation because of the data that could be intercepted from this way of working.
SNMP can easily retrieve (for example) firmware versions / operating systems version / patch level from a lot of network devices and is most likely a gold mine for someone malicious.

Even if you make this optional and clear that its not recommended its really not a good idea for us. It could also become an attack vector (i.e : someone access OCS server and change this value for data stealing purpose).

I remain available if you want to discuss more about this subject :)

Regards,
Gilles.

**Comment by Artem-Mamzikov** [comment]
Thanks for the answer! I wanted to say that by default, https is enabled in ocs Inventory and add a switch with the notification "that there is an activation on a secure connection and data leakage is possible.... you still want to continue enabling http" and the responsibility is no longer on the developer. Even as an option make PSK (OpenSSL; GnuTLS; mbed TLS)
it is free of charge. You need to buy an ssl certificate for 1 year, then you need to replace it everywhere and buy it again, this is not quite suitable for me(.
I am under my responsibility more satisfied with 1 option with switching, or if you can write to me personally or comment below how I can make myself http for snmp.
Thanks!

**Comment by gillesdubois** [comment]
I understand but I don't think that will be a priority to implement such behavior.

Also, if you don't want to buy a certificate or a 1 year valid one you can generate a Self-Signed certificate. 
It will allow you to set longer validity thus  you won't have to plan a certificate renewal every year.

Regards,
Gilles.

**Comment by Artem-Mamzikov** [comment]
Thank you I understand you, until you have to give up snmp.
