### ISSUE TITLE
FEATURE: software REST API

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/OCSInventory-Server#286]
### Problem's description
I would like to have GET routes for softwares through REST API.
In particular, I would like to have a route for such a query:
`select CONCAT(SN.NAME,SV.VERSION),COUNT(1) from software as SOFT left join software_name as SN on SN.id=SOFT.NAME_ID left join software_version as SV on SV.id=SOFT.VERSION_ID GROUP BY 1`
How would I go for that in a way that you could accept as PR?

**Comment by gillesdubois** [comment]
Hi @StCyr 

In order to create a PR, you'll need to create a proper route API.
You can take example on computers routes that already exist.

The PR need to be in the same logic as the other API structure.

If you want a software dedicated route, it will be something like : 
* /ocsapi/v1/softwares/1 
* /ocsapi/v1/softwares/mysoftwarename
* /ocsapi/v1/softwares/mysoftwarename/myversion

The second "condition" is that you need to also create the documentation on our Wiki.

We remain available if you have any question :) 

Regards,
Gilles.

**Comment by StCyr** [comment]
PR created => https://github.com/OCSInventory-NG/OCSInventory-Server/pull/287

If it's ok, I'll write the doc
