### ISSUE TITLE
Ocs Inventory Server  2.9.2 issue

### ISSUE THREAD

**Issue by naccey** [OCSInventory-NG/OCSInventory-Server#384]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : 
Ubuntu 20.04.4 LTS
### Server informations
Perl version :  perl 5, version 30
Mysql / Mariadb / Percona version :  
MySQL Community Server - GPL version 8.0.20
### OCS Inventory informations
Ocs server version : 
2.9.2
### Problem's description
*Describe your problem here*
Hello All,
I have few problems below and attacheded screenshot
How to solve theese problems?
Thanks for yours support sincerly ;)

mysql error DBD::mysql::db do failed: Duplicate entry '3071' for key 'accountinfo.PRIMARY' at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Inventory/Update/AccountInfos.pm line 66.

DBD::mysql::db do failed: The table 'prolog_conntrack' is full at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Communication/Session.pm line 46.

DBD::mysql::db do failed: Duplicate entry 'SESSION-CLEAN' for key 'engine_mutex.PRIMARY' at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Communication/Session.pm line 59.

DBD::mysql::st execute failed: Deadlock found when trying to get lock; try restarting transaction at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Inventory/Software.pm line 59.
![mysql_failed](https://user-images.githubusercontent.com/15703383/168803001-24477535-6ecb-4508-9100-1eb069583f59.JPG)

**Comment by Asimatasert** [comment]
Hello , 
For This Dublicate Solition

> mysql error DBD::mysql::db do failed: Duplicate entry '3071' for key 'accountinfo.PRIMARY' at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Inventory/Update/AccountInfos.pm line 66.

> DBD::mysql::db do failed: Duplicate entry 'SESSION-CLEAN' for key 'engine_mutex.PRIMARY' at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Communication/Session.pm line 59.

This problem will solve AccountInfos.pm line 66 and Session.pm line 59  you need to have a check before if statement with a sql query, it's problem weld to insert a same record in to db , ocs devs must have forgotten to make this line

Sample php function for crush the issue

function checkIfExist($e){
$q="SELECT * FROM DBTABLENAME WHERE col=$e"
if(!$q){
$q="INSERT into DBTABLENAME col values ($e)"
}
else{die;}
}

**Comment by charleneauger** [comment]
Hi @naccey and @jjmg84 ,

Can you run the following queries for all problematic tables and return the result to me :
- `DESCRIBE my_table;`
- ` SELECT TABLE STATUS FROM 'my_database' WHERE name LIKE 'my_table';`
- `SELECT count(*) FROM my_table;`

@naccey : the PR #405 should fix deadlock on software.pm

Best regards,
Charlene

**Comment by jjmg84** [comment]
Hi, i atach one line of every error: 

DBD::mysql::db do failed: Duplicate entry '50581' for key 'PRIMARY' at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/System.pm line 246.
Line 246 makes a insert: 'INSERT INTO locks(HARDWARE_ID, ID, SINCE) VALUES(?,?,NOW())
![imagen](https://user-images.githubusercontent.com/77288568/195639554-4c8cf3d1-d4c0-4b22-8a14-3122ad5d679d.png)
![imagen](https://user-images.githubusercontent.com/77288568/195640328-23c6bbb6-1e01-4cbc-ad0b-1e76e5c6b536.png)
![imagen](https://user-images.githubusercontent.com/77288568/195640658-661fd1d4-2f70-473e-ad18-357ee7684a12.png)


DBD::mysql::db do failed: Duplicate entry '66109' for key 'PRIMARY' at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Inventory/Update/AccountInfos.pm line 66.
line 66 makes a insert: 'INSERT INTO accountinfo(HARDWARE_ID) VALUES(?)'
![imagen](https://user-images.githubusercontent.com/77288568/195641050-b7afacd9-8d82-435e-bfc0-07d5d654d33b.png)
![imagen](https://user-images.githubusercontent.com/77288568/195641128-d6e89d6d-636f-47bd-8ac3-49c8bc4da449.png)
![imagen](https://user-images.githubusercontent.com/77288568/195641260-a29e5b58-8a54-4658-bcf0-0ce4bb38d793.png)


DBD::mysql::db do failed: Duplicate entry 'SESSION-CLEAN' for key 'PRIMARY' at /usr/local/share/perl/5.30.0/Apache/Ocsinventory/Server/Communication/Session.pm line 59.
Line 59 makes a insert: INSERT INTO engine_mutex(NAME, PID, TAG) VALUES('SESSION',?,'CLEAN')
![imagen](https://user-images.githubusercontent.com/77288568/195641576-ea218a98-2524-4e97-a604-26aaa4f94319.png)
![imagen](https://user-images.githubusercontent.com/77288568/195641616-bc76e630-d862-4761-a8a3-c7955a4e3033.png)
![imagen](https://user-images.githubusercontent.com/77288568/195641717-4c20b2b1-deee-432b-bbfc-f662dbf990a6.png)


Here are the data @charleneauger 

thanks!

**Comment by charleneauger** [comment]
Hi @naccey, @Asimatasert, @jjmg84,

After analysis, it turns out that the server executes INSERT queries without verifying the existence of the data.
We have added this correction to our Roadmap.

Regards,
Charlene
