### ISSUE TITLE
Support PostgreSQL

### ISSUE THREAD

**Issue by nohnaimer** [OCSInventory-NG/OCSInventory-Server#386]
Hello,
Do you plan to support PostgreSQL?

**Comment by gillesdubois** [comment]
Hi,

We are planning on reworking the inventory engine with an ORM :)
PSQL will definitely be in the compatibility list.

Regards,
Gilles.

**Comment by nohnaimer** [comment]
Hi,

ORM? Link on TODO list? Are there any deadlines?

**Comment by gillesdubois** [comment]
You can look at this page to have a example of what is an ORM : https://ilovedjango.com/django/orm/understanding-the-django-orm-object-relational-mapping/

Deadline is most likely next year by now since its not an urgent priority.
We are waiting for several other feature / changes before pushing the ORM implementation.
