### ISSUE TITLE
DBD::mysql::db do failed: Illegal mix of collations

### ISSUE THREAD

**Issue by nntu** [OCSInventory-NG/OCSInventory-Server#6]
hi, sorry my english :)
my os:  Linux app 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 
mysql : 5.6 
DATABASE `ocsweb` /*!40100 COLLATE 'utf8_general_ci' */
error : -e: DBD::mysql::db do failed: Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' at /usr/local/share/perl/5.20.2/Apache/Ocsinventory/Server/Inventory/Cache.pm line 34

i find google and found: https://www.webgui.org/etcetera/dbdmysqlst-execute-failed-illegal-mix-of-collations/1
[mysqld]
default-character-set=utf8
character-set-server = utf8
collation-server = utf8_general_ci

[client]
default-character-set=utf8

so still faulty . 
thanks

**Comment by gillesdubois** [comment]
Hello, as your other issue i cannot reproduce this bug : 

If you're sure that is a bug and not a configuration / installation problems you should re-post one issue with more details. 
See this issue answer for more details on what you need to post for a quick and accurate reply =>  https://github.com/OCSInventory-NG/OCSInventory-Server/issues/7 .

Sorry for inconvenience you met.
Regards, Gilles Dubois.

**Comment by netexpertise** [comment]
Hi,
I got the exact same error

I didn't have too much time to troubleshoot which table was causing the problem so I looked for all tables containing the "cache" keyword since it is related to the cache.pm file.

- groups_cache
- hardware_osname_cache
- registry_name_cache
- registry_regvalue_cache
- softwares_name_cache

I looked for the collation field setting with
mysql> show full columns from hardware_osname_cache;
| Field  | Type         | Collation         | ...
| ID     | ...
| OSNAME | varchar(255) | latin1_swedish_ci | ...

and converted them to utf8
ALTER TABLE hardware_osname_cache MODIFY OSNAME VARCHAR(255) COLLATE utf8_general_ci;
ALTER TABLE registry_name_cache MODIFY NAME VARCHAR(255) COLLATE utf8_general_ci;
ALTER TABLE registry_regvalue_cache MODIFY REGVALUE VARCHAR(255) COLLATE utf8_general_ci;
ALTER TABLE softwares_name_cache MODIFY NAME VARCHAR(255) COLLATE utf8_general_ci;

Errors in logs have gone away.
Those fields must have been created with your default Mysql collation property I suppose.

David
