### ISSUE TITLE
Request for user agent version string for unofficial ocs inventory agent for Thinstation

### ISSUE THREAD

**Issue by jackburton79** [OCSInventory-NG/OCSInventory-Server#69]
Where I work we're using ocsinventory-ng to keep track of our computers. Since we're also using Thinstation and PXE booting some computers, I wrote an "alternative" and unofficial ocs inventory agent which runs on Thinstation.
I'm requesting a custom user agent version string, if possible, since currently I'm using the string "OCS-NG_unified_unix_agent_v"
The agent is here: 
https://github.com/jackburton79/agent

Thanks

**Comment by kapouik** [comment]
As you are made an unofficial agent, you can put what you want as user agent.

To validate it, just go in ocsinventory-server.conf and edit this section : 

`# ===== EXTERNAL USERAGENTS =====

  #Path for external useragents reference file
  #!! WARNING !! : external agents may not be supported by OCS NG Community ! 
  #PerlSetEnv OCS_OPT_EXT_USERAGENTS_FILE_PATH /tmp/yourfile.txt
`

You will be able to insert your custom user agent in the file /tmp/yourfile.txt as it (for exemple) : 

`jack-inventory-agent v1.0
jack-inventory-agent_v1.2
`
--------

We just discover your work in the OCS Inventory Team and it is really cool. 
I just see two problems : 

- you call the binary ocsinventory-agent : it better to find another name because of name conflict with official agent (if someone want to use both)
- I don't have see any method in the makefile to create a strictly static binary : it can be cool if someone want to deploy a simple binary on many different distribution without dependancies problem.
